version: "3.9"
services:
  webapi:
    build: .
    ports:
      - "5000:80"
  sqldb:
      image: mcr.microsoft.com/mssql/server:2019-latest
      environment:
        - SA_PASSWORD=Pass1*word0
        - ACCEPT_EULA=Y
      ports:
        - "1440:1433"